# Generated by Django 4.1.1 on 2022-09-21 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 23, 56, 43, 127971, tzinfo=datetime.timezone.utc)),
        ),
    ]
