# Generated by Django 4.1.1 on 2022-09-21 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 21, 23, 56, 55, 620228, tzinfo=datetime.timezone.utc)),
        ),
    ]
