# Generated by Django 4.1.1 on 2022-09-22 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='Created at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 0, 1, 51, 856973, tzinfo=datetime.timezone.utc)),
        ),
    ]
