# Generated by Django 4.1.1 on 2022-09-22 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_created_at_post_created at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Created at',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 21, 12, 23, 164486)),
        ),
    ]
